server:
  port: 8081
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa :
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl : true
    hibernate:
      ddl-auto: update
    show_sql : true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    # 로그 레벨 : trace < debug < info < error  순서의 로그레벨을 가짐 -> 즉 info 으로 설정시 trace / debug 로그는 출력 x
    root : info
    # default 값 info

  # 로그 파일 경로와 파일명 지정
  file :
    name : logs/app.log